GET http://localhost:3001/items

###

POST http://localhost:3001/item/new
Content-Type: application/json

{
    "itemName": "Jeans"
}

###

DELETE http://localhost:3001/item/delete/61ca2cb50603f551e0ba750b

###

PUT http://localhost:3001/item/bought/61ca2c850603f551e0ba7507

###

PUT http://localhost:3001/item/increment/61ca664f7176359ca47485a8

###

PUT http://localhost:3001/item/decrement/61ca66557176359ca47485aa
